version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "danielkinahan"
  # Check for Docker image updates
  - package-ecosystem: "docker"
    directory: "/caddy-porkbun"
    schedule:
      interval: "daily"
    assignees:
      - "danielkinahan"